name: flutter_drawio
description: A flutter package for drawing on a canvas with an api provided for serialization and deserialization of the drawn data.
version: 0.0.1+1
homepage: https://github.com/folaoluwafemi/flutter_drawio

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: